# Generated by Django 5.1.1 on 2024-09-21 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0002_alter_studysession_user'),
        ('users', '0004_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studysession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='users.user'),
        ),
    ]
