# Generated by Django 5.1.1 on 2024-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='New User', error_messages={'invalid_name': 'Name must contain only letters and spaces.', 'max_length': 'The name cannot exceed 255 characters.'}, help_text='Full name. Letters and spaces only. 255 characters or fewer.', max_length=255),
            preserve_default=False,
        ),
    ]
